import type { IssueReport } from '../types';

const placeholder = (name: string, ext = 'jpg') => `/images/${name}.${ext}`;

export const mockIssueReports: IssueReport[] = [
  {
    id: '001-2025',
    title: 'Jalan Berlubang di Jalan Sudirman',
    description: 'Lubang besar di jalur cepat menyebabkan kemacetan parah dan berpotensi membahayakan pengendara motor.',
    category: 'jalan',
    severityScore: 8,
    status: 'open',
    source: 'citizen',
    imageUrl: placeholder('jalan-berlubang', 'jpg'),
    latitude: -6.2088,
    longitude: 106.8456,
    reportedAt: '2025-05-10T08:30:00Z',
    lastConfirmedAt: '2025-07-20T14:22:00Z',
    confirmationCount: 12,
    location: 'Jalan Sudirman, Jakarta Selatan',
    statusHistory: [
      { status: 'new', timestamp: '2025-05-10T08:30:00Z', message: 'Laporan baru diterima. Terima kasih.' },
      { status: 'open', timestamp: '2025-05-12T09:00:00Z', message: 'Status berubah menjadi Open.' },
    ],
  },
  {
    id: '002-2025',
    title: 'Jembatan Goyang di Ciliwung',
    description: 'Jembatan penyeberangan yang goyah dan berbahaya, sudah banyak warga melaporkan.',
    category: 'jembatan',
    severityScore: 9,
    status: 'closed',
    source: 'ai_media',
    imageUrl: placeholder('jembatan-rusak', 'jpg'),
    latitude: -6.2146,
    longitude: 106.8543,
    reportedAt: '2025-06-20T10:15:00Z',
    lastConfirmedAt: '2025-07-19T09:45:00Z',
    confirmationCount: 8,
    location: 'Sungai Ciliwung, Jakarta Pusat',
    statusHistory: [
      { status: 'new', timestamp: '2025-06-20T10:15:00Z', message: 'Laporan baru diterima. Terima kasih.' },
      { status: 'open', timestamp: '2025-06-21T08:00:00Z', message: 'Status berubah menjadi Open.' },
      { status: 'closed', timestamp: '2025-07-19T09:45:00Z', message: 'Laporan diproses dan masalah telah diselesaikan. Terima kasih.' },
    ],
  },
  {
    id: '003-2025',
    title: 'Tumpukan Sampah di Taman Anggrek',
    description: 'Sampah menumpuk sudah 2 minggu tidak diangkut oleh petugas kebersihan.',
    category: 'sampah',
    severityScore: 6,
    status: 'new',
    source: 'citizen',
    imageUrl: placeholder('tumpukan-sampah', 'jpg'),
    latitude: -6.1896,
    longitude: 106.7973,
    reportedAt: '2025-07-18T16:40:00Z',
    lastConfirmedAt: '2025-07-21T11:10:00Z',
    confirmationCount: 15,
    location: 'Taman Anggrek, Jakarta Barat',
    statusHistory: [
      { status: 'new', timestamp: '2025-07-18T16:40:00Z', message: 'Laporan baru diterima. Terima kasih.' },
    ],
  },
  {
    id: '004-2025',
    title: 'Bangunan Runtuh di Kebon Jeruk',
    description: 'Bagian lantai 2 bangunan tua ambruk, warga sekitar perlu dievakuasi segera.',
    category: 'bangunan',
    severityScore: 10,
    status: 'archived',
    source: 'ai_media',
    imageUrl: placeholder('bangunan-runtuh', 'jpg'),
    latitude: -6.1962,
    longitude: 106.7833,
    reportedAt: '2025-04-10T07:20:00Z',
    lastConfirmedAt: '2025-06-30T18:00:00Z',
    confirmationCount: 5,
    location: 'Kebon Jeruk, Jakarta Barat',
    statusHistory: [
      { status: 'new', timestamp: '2025-04-10T07:20:00Z', message: 'Laporan baru diterima. Terima kasih.' },
      { status: 'open', timestamp: '2025-04-11T09:00:00Z', message: 'Status berubah menjadi Open.' },
      { status: 'closed', timestamp: '2025-06-28T15:00:00Z', message: 'Laporan diproses dan masalah telah diselesaikan.' },
      { status: 'archived', timestamp: '2025-06-30T18:00:00Z', message: 'Status berubah menjadi Archived.' },
    ],
  },
  {
    id: '005-2025',
    title: 'Drainase Tersumbat di Senayan',
    description: 'Saluran air penuh lumpur, selalu banjir setiap kali hujan turun.',
    category: 'drainase',
    severityScore: 7,
    status: 'new',
    source: 'citizen',
    imageUrl: placeholder('drainase-tersumbat', 'jpg'),
    latitude: -6.2241,
    longitude: 106.8000,
    reportedAt: '2025-07-15T12:00:00Z',
    lastConfirmedAt: '2025-07-21T10:30:00Z',
    confirmationCount: 20,
    location: 'Senayan, Jakarta Selatan',
    statusHistory: [
      { status: 'new', timestamp: '2025-07-15T12:00:00Z', message: 'Laporan baru diterima. Terima kasih.' },
    ],
  },
  {
    id: '006-2025',
    title: 'Jalan Retak di Pancoran',
    description: 'Retakan memanjang di seberang mall yang semakin parah.',
    category: 'jalan',
    severityScore: 5,
    status: 'open',
    source: 'citizen',
    imageUrl: placeholder('jalan-retak', 'jpg'),
    latitude: -6.2405,
    longitude: 106.8286,
    reportedAt: '2025-06-25T09:05:00Z',
    lastConfirmedAt: '2025-07-18T15:40:00Z',
    confirmationCount: 7,
    location: 'Pancoran, Jakarta Selatan',
    statusHistory: [
      { status: 'new', timestamp: '2025-06-25T09:05:00Z', message: 'Laporan baru diterima. Terima kasih.' },
      { status: 'open', timestamp: '2025-06-26T10:00:00Z', message: 'Status berubah menjadi Open.' },
    ],
  },
  {
    id: '007-2025',
    title: 'Sampah Plastik di Sungai',
    description: 'Sampah plastik mengambang di aliran sungai dan menghalangi air mengalir.',
    category: 'sampah',
    severityScore: 6,
    status: 'open',
    source: 'ai_media',
    imageUrl: placeholder('sampah-plastik', 'jpg'),
    latitude: -6.1450,
    longitude: 106.8190,
    reportedAt: '2025-06-01T14:30:00Z',
    lastConfirmedAt: '2025-07-20T17:20:00Z',
    confirmationCount: 11,
    location: 'Kali Besar, Jakarta Utara',
    statusHistory: [
      { status: 'new', timestamp: '2025-06-01T14:30:00Z', message: 'Laporan baru diterima. Terima kasih.' },
      { status: 'open', timestamp: '2025-06-03T08:00:00Z', message: 'Status berubah menjadi Open.' },
    ],
  },
  {
    id: '008-2025',
    title: 'Drainase Bocor di Ciputat',
    description: 'Air limbah merembes ke permukaan jalan menyebabkan genangan berbau.',
    category: 'drainase',
    severityScore: 7,
    status: 'new',
    source: 'citizen',
    imageUrl: placeholder('drainase-bocor', 'jpg'),
    latitude: -6.2956,
    longitude: 106.7346,
    reportedAt: '2025-07-19T11:15:00Z',
    lastConfirmedAt: '2025-07-21T08:50:00Z',
    confirmationCount: 9,
    location: 'Ciputat, Tangerang Selatan',
    statusHistory: [
      { status: 'new', timestamp: '2025-07-19T11:15:00Z', message: 'Laporan baru diterima. Terima kasih.' },
    ],
  },
];
